# Generated by Django 5.1.3 on 2024-11-30 11:13

import mainlogin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True, db_column="USER_NAME", max_length=150, null=True
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, db_column="PASSWORD", max_length=150, null=True
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        blank=True, db_column="User_Type", max_length=50, null=True
                    ),
                ),
                (
                    "f_name",
                    models.CharField(
                        blank=True, db_column="F_NAME", max_length=150, null=True
                    ),
                ),
                (
                    "l_name",
                    models.CharField(
                        blank=True, db_column="L_NAME", max_length=150, null=True
                    ),
                ),
                ("dob", models.DateField(blank=True, db_column="DOB", null=True)),
                (
                    "mobile",
                    models.CharField(
                        blank=True, db_column="MOBILE", max_length=15, null=True
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, db_column="EMAIL", max_length=50, null=True
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, db_column="ADDRESS", max_length=250, null=True
                    ),
                ),
                (
                    "profile_photo",
                    models.CharField(
                        blank=True, db_column="PROFILE_PHOTO", max_length=250, null=True
                    ),
                ),
                (
                    "crt_date",
                    models.DateTimeField(blank=True, db_column="CRT_DATE", null=True),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=mainlogin.models.filepath
                    ),
                ),
                (
                    "passwordstatus",
                    models.CharField(
                        blank=True,
                        db_column="passwordchange",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "activation",
                    models.CharField(
                        blank=True, db_column="activation", max_length=100, null=True
                    ),
                ),
                (
                    "work_location",
                    models.CharField(
                        blank=True, db_column="work_location", max_length=100, null=True
                    ),
                ),
                (
                    "office_manager",
                    models.CharField(
                        blank=True,
                        db_column="office_manager",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "LOGIN",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UserType",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "user_type",
                    models.CharField(
                        blank=True, db_column="USER_TYPE", max_length=50, null=True
                    ),
                ),
            ],
            options={
                "db_table": "USER_TYPE",
                "managed": True,
            },
        ),
    ]
