# Generated by Django 3.2.15 on 2022-09-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainlogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login',
            options={'managed': True},
        ),
    ]
