# Generated by Django 5.1.3 on 2024-11-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_id", models.CharField(blank=True, max_length=50, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("date", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "currentdate",
                    models.CharField(
                        blank=True, db_column="currentDate", max_length=150, null=True
                    ),
                ),
            ],
            options={
                "db_table": "activities",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Empdata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emp_id",
                    models.CharField(
                        blank=True, db_column="EMP_ID", max_length=150, null=True
                    ),
                ),
                (
                    "mon",
                    models.CharField(
                        blank=True, db_column="mon", max_length=150, null=True
                    ),
                ),
                (
                    "tue",
                    models.CharField(
                        blank=True, db_column="tue", max_length=150, null=True
                    ),
                ),
                (
                    "wed",
                    models.CharField(
                        blank=True, db_column="wed", max_length=150, null=True
                    ),
                ),
                (
                    "thu",
                    models.CharField(
                        blank=True, db_column="thu", max_length=150, null=True
                    ),
                ),
                (
                    "fri",
                    models.CharField(
                        blank=True, db_column="fri", max_length=150, null=True
                    ),
                ),
                (
                    "sat",
                    models.CharField(
                        blank=True, db_column="sat", max_length=150, null=True
                    ),
                ),
                (
                    "sun",
                    models.CharField(
                        blank=True, db_column="sun", max_length=150, null=True
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        blank=True, db_column="PROJECT_NAME", max_length=150, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, db_column="status", max_length=150, null=True
                    ),
                ),
                (
                    "start",
                    models.CharField(
                        blank=True, db_column="start", max_length=150, null=True
                    ),
                ),
                (
                    "end",
                    models.CharField(
                        blank=True, db_column="[end]", max_length=150, null=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_column="NAME", max_length=150, null=True
                    ),
                ),
                (
                    "total",
                    models.CharField(
                        blank=True, db_column="total", max_length=150, null=True
                    ),
                ),
                (
                    "totals",
                    models.CharField(
                        blank=True, db_column="week_total", max_length=150, null=True
                    ),
                ),
                (
                    "statushr",
                    models.CharField(
                        blank=True, db_column="status_hr", max_length=150, null=True
                    ),
                ),
                (
                    "date_created",
                    models.CharField(
                        blank=True, db_column="date_created", max_length=150, null=True
                    ),
                ),
                (
                    "manager_id",
                    models.CharField(
                        blank=True, db_column="manager_id", max_length=150, null=True
                    ),
                ),
                (
                    "hr_id",
                    models.CharField(
                        blank=True, db_column="hr_id", max_length=150, null=True
                    ),
                ),
                (
                    "assigned",
                    models.CharField(
                        blank=True, db_column="assigned", max_length=150, null=True
                    ),
                ),
                (
                    "work_location",
                    models.CharField(
                        blank=True, db_column="work_location", max_length=150, null=True
                    ),
                ),
                (
                    "office_manager",
                    models.CharField(
                        blank=True,
                        db_column="office_manager",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "status_om",
                    models.CharField(
                        blank=True, db_column="status_om", max_length=150, null=True
                    ),
                ),
            ],
            options={
                "db_table": "empdata",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="EmpLeaves",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emp_id",
                    models.CharField(
                        blank=True, db_column="EMP_ID", max_length=150, null=True
                    ),
                ),
                (
                    "emp_name",
                    models.CharField(
                        blank=True, db_column="EMP_NAME", max_length=150, null=True
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        blank=True, db_column="LEAVE_TYPE", max_length=150, null=True
                    ),
                ),
                (
                    "from_dt",
                    models.CharField(
                        blank=True, db_column="FROM", max_length=150, null=True
                    ),
                ),
                (
                    "to_dt",
                    models.CharField(
                        blank=True, db_column="TO", max_length=150, null=True
                    ),
                ),
                (
                    "day_type",
                    models.CharField(
                        blank=True, db_column="DAY_TYPE", max_length=150, null=True
                    ),
                ),
                (
                    "no_of_days",
                    models.CharField(
                        blank=True, db_column="NO_OF_DAYS", max_length=150, null=True
                    ),
                ),
                (
                    "remaining_leaves",
                    models.CharField(
                        blank=True,
                        db_column="REMAINING_LEAVES",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "leave_taken",
                    models.CharField(
                        blank=True, db_column="LEAVE_TAKEN", max_length=150, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, db_column="status", max_length=150, null=True
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, db_column="reason", max_length=350, null=True
                    ),
                ),
                (
                    "date_applied",
                    models.CharField(
                        blank=True, db_column="date_applied", max_length=150, null=True
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        blank=True, db_column="user_type", max_length=150, null=True
                    ),
                ),
                (
                    "valid_leaves",
                    models.CharField(
                        blank=True, db_column="valid_leaves", max_length=150, null=True
                    ),
                ),
                (
                    "paid_leaves",
                    models.CharField(
                        blank=True, db_column="paid_leaves", max_length=150, null=True
                    ),
                ),
                (
                    "hr_id",
                    models.CharField(
                        blank=True, db_column="hr_id", max_length=150, null=True
                    ),
                ),
                (
                    "manager_id",
                    models.CharField(
                        blank=True, db_column="manager_id", max_length=150, null=True
                    ),
                ),
            ],
            options={
                "db_table": "EMP_LEAVES",
                "managed": True,
            },
        ),
    ]
