# Generated by Django 3.2.15 on 2022-09-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empdata',
            name='name',
            field=models.CharField(blank=True, db_column='NAME', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='empdata',
            name='total',
            field=models.CharField(blank=True, db_column='total', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='empdata',
            name='totals',
            field=models.CharField(blank=True, db_column='week_total', max_length=150, null=True),
        ),
    ]
