# Generated by Django 5.1.3 on 2024-11-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PhaseVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project",
                    models.CharField(
                        blank=True, db_column="PROJECT", max_length=150, null=True
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        blank=True, db_column="PHASE", max_length=150, null=True
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True, db_column="VERSION", max_length=150, null=True
                    ),
                ),
                (
                    "start_date",
                    models.CharField(
                        blank=True, db_column="START_DATE", max_length=150, null=True
                    ),
                ),
                (
                    "create_date",
                    models.CharField(
                        blank=True, db_column="CREATE_DATE", max_length=150, null=True
                    ),
                ),
                (
                    "time_period",
                    models.CharField(
                        blank=True, db_column="TIME_PERIOD", max_length=150, null=True
                    ),
                ),
                (
                    "end_date",
                    models.CharField(
                        blank=True, db_column="END_DATE", max_length=150, null=True
                    ),
                ),
            ],
            options={
                "db_table": "PHASE_VERSION",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TaskCrew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True, db_column="TASK_ID", max_length=150, null=True
                    ),
                ),
                (
                    "employee_name",
                    models.CharField(
                        blank=True, db_column="EMPLOYEE", max_length=150, null=True
                    ),
                ),
                (
                    "create_date",
                    models.CharField(
                        blank=True, db_column="CREATE_DATE", max_length=150, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, db_column="STATUS", max_length=150, null=True
                    ),
                ),
            ],
            options={
                "db_table": "TASK_CREW",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TaskFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True, db_column="TASK_ID", max_length=100, null=True
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True, db_column="FILE_NAME", max_length=250, null=True
                    ),
                ),
                (
                    "create_date",
                    models.CharField(
                        blank=True,
                        db_column="CREATE_DATEtime",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "TASK_FILES",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_id",
                    models.CharField(
                        blank=True, db_column="PROJECT_ID", max_length=150, null=True
                    ),
                ),
                (
                    "team_id",
                    models.CharField(
                        blank=True, db_column="TEAM_ID", max_length=150, null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, db_column="DESCRIPTION", null=True),
                ),
                (
                    "assigning_date",
                    models.CharField(
                        blank=True,
                        db_column="ASSIGNING_DATE",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "target_date",
                    models.CharField(
                        blank=True, db_column="TARGET_DATE", max_length=150, null=True
                    ),
                ),
                (
                    "complete_date",
                    models.CharField(
                        blank=True, db_column="COMPLTE_DATE", max_length=150, null=True
                    ),
                ),
                (
                    "manager_id",
                    models.CharField(
                        blank=True, db_column="MANAGER_ID", max_length=150, null=True
                    ),
                ),
                (
                    "hr_id",
                    models.CharField(
                        blank=True, db_column="HR_ID", max_length=150, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, db_column="STATUS", max_length=150, null=True
                    ),
                ),
                (
                    "crt_date",
                    models.CharField(
                        blank=True, db_column="CRT_DATE", max_length=150, null=True
                    ),
                ),
                (
                    "ui",
                    models.CharField(
                        blank=True, db_column="UI", max_length=150, null=True
                    ),
                ),
                (
                    "database",
                    models.CharField(
                        blank=True, db_column="DATABASE", max_length=150, null=True
                    ),
                ),
                (
                    "backend",
                    models.CharField(
                        blank=True, db_column="BACKEND", max_length=150, null=True
                    ),
                ),
                (
                    "projec_task_id",
                    models.CharField(
                        blank=True,
                        db_column="PROJEC_TASK_ID",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        blank=True, db_column="PHASE", max_length=150, null=True
                    ),
                ),
                (
                    "project_version",
                    models.CharField(
                        blank=True,
                        db_column="PROJECT_VERSION",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "task_heading",
                    models.CharField(
                        blank=True, db_column="TASK_HEADING", max_length=150, null=True
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        blank=True, db_column="TASK_TYPE", max_length=150, null=True
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True, db_column="PRIORITY", max_length=150, null=True
                    ),
                ),
                (
                    "assignee",
                    models.CharField(
                        blank=True, db_column="ASSIGNEE", max_length=150, null=True
                    ),
                ),
            ],
            options={
                "db_table": "TASKS",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TasksChats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True, db_column="TASK_ID", max_length=150, null=True
                    ),
                ),
                (
                    "team_id",
                    models.CharField(
                        blank=True, db_column="TEAM_ID", max_length=150, null=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, db_column="DESCRIPTION", max_length=150, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, db_column="STATUS", max_length=150, null=True
                    ),
                ),
                (
                    "crt_date",
                    models.CharField(
                        blank=True, db_column="CRT_DATE", max_length=150, null=True
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True, db_column="USER_NAME", max_length=150, null=True
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        blank=True, db_column="USER_ID", max_length=150, null=True
                    ),
                ),
            ],
            options={
                "db_table": "TASKS_CHATS",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TasksLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_id",
                    models.CharField(
                        blank=True, db_column="PROJECT_ID", max_length=150, null=True
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True, db_column="TASK_ID", max_length=150, null=True
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True, db_column="FROM_STATUS", max_length=150, null=True
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        blank=True, db_column="TO_STATUS", max_length=150, null=True
                    ),
                ),
                (
                    "assigning_date",
                    models.CharField(
                        blank=True,
                        db_column="ASSIGNING_DATE",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "target_date",
                    models.CharField(
                        blank=True, db_column="TARGET_DATE", max_length=150, null=True
                    ),
                ),
                (
                    "complte_date",
                    models.CharField(
                        blank=True, db_column="COMPLTE_DATE", max_length=150, null=True
                    ),
                ),
                (
                    "manager_id",
                    models.CharField(
                        blank=True, db_column="MANAGER_ID", max_length=150, null=True
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        blank=True, db_column="USER_ID", max_length=150, null=True
                    ),
                ),
                (
                    "crt_date",
                    models.CharField(
                        blank=True, db_column="CRT_DATE", max_length=150, null=True
                    ),
                ),
            ],
            options={
                "db_table": "TASKS_LOGS",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Versions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project",
                    models.CharField(
                        blank=True, db_column="project", max_length=150, null=True
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True, db_column="version", max_length=150, null=True
                    ),
                ),
                (
                    "create_date",
                    models.CharField(
                        blank=True, db_column="create_date", max_length=150, null=True
                    ),
                ),
            ],
            options={
                "db_table": "VERSIONS",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emp_id",
                    models.CharField(
                        blank=True, db_column="emp_id", max_length=150, null=True
                    ),
                ),
                (
                    "emp_name",
                    models.CharField(
                        blank=True, db_column="emp_name", max_length=150, null=True
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, db_column="message", null=True),
                ),
                ("date", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "current_date",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "emp",
                    models.CharField(
                        blank=True, db_column="emp", max_length=10, null=True
                    ),
                ),
                (
                    "hr",
                    models.CharField(
                        blank=True, db_column="hr", max_length=10, null=True
                    ),
                ),
                (
                    "manager",
                    models.CharField(
                        blank=True, db_column="manager", max_length=10, null=True
                    ),
                ),
                (
                    "manager_id",
                    models.CharField(
                        blank=True, db_column="manager_id", max_length=10, null=True
                    ),
                ),
                (
                    "hr_id",
                    models.CharField(
                        blank=True, db_column="hr_id", max_length=10, null=True
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Ratings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_id", models.CharField(blank=True, max_length=150, null=True)),
                ("rating", models.CharField(blank=True, max_length=150, null=True)),
                ("startdate", models.CharField(blank=True, max_length=150, null=True)),
                ("enddate", models.CharField(blank=True, max_length=150, null=True)),
                ("createdate", models.CharField(blank=True, max_length=150, null=True)),
                ("hr_id", models.CharField(blank=True, max_length=150, null=True)),
                ("manager_id", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "manager_comment",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "employee_comment",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "emp_comm_tue",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "emp_comm_wed",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "emp_comm_thu",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "emp_comm_fri",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "emp_comm_sat",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
            ],
            options={
                "db_table": "ratings",
                "managed": True,
            },
        ),
    ]
